"""add_attempt_tracking_fields

Revision ID: 4b0c30b467ac
Revises: 015
Create Date: 2025-12-13 19:30:35.500481

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4b0c30b467ac'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_cost_config_api_name', table_name='api_cost_config')
    op.drop_index('ix_api_cost_config_is_active', table_name='api_cost_config')
    op.drop_constraint('unique_active_config', 'api_cost_config', type_='unique')
    op.alter_column('blocked_domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('blocked_domains_domain_key', 'blocked_domains', type_='unique')
    op.drop_index('idx_blocked_domains_domain', table_name='blocked_domains')
    op.create_index(op.f('ix_blocked_domains_domain'), 'blocked_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_blocked_domains_id'), 'blocked_domains', ['id'], unique=False)
    op.drop_index('ix_financial_transactions_api', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_date', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_project', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_quote', table_name='financial_transactions')
    op.create_index(op.f('ix_financial_transactions_api_name'), 'financial_transactions', ['api_name'], unique=False)
    op.create_index(op.f('ix_financial_transactions_project_id'), 'financial_transactions', ['project_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.drop_index('ix_items_uniqueness', table_name='items')
    op.drop_index('ix_materials_codigo', table_name='materials')
    op.create_index(op.f('ix_materials_codigo'), 'materials', ['codigo'], unique=False)
    op.drop_constraint('project_bank_prices_config_version_id_fkey', 'project_bank_prices', type_='foreignkey')
    op.create_foreign_key(None, 'project_bank_prices', 'project_config_versions', ['config_version_id'], ['id'])
    op.drop_constraint('project_config_versions_project_id_fkey', 'project_config_versions', type_='foreignkey')
    op.create_foreign_key(None, 'project_config_versions', 'projects', ['project_id'], ['id'])
    op.drop_column('project_config_versions', 'tolerancia_variacao_vs_banco_percent')
    op.add_column('quote_requests', sa.Column('attempt_number', sa.Integer(), nullable=True))
    op.add_column('quote_requests', sa.Column('original_quote_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote_requests', 'quote_requests', ['original_quote_id'], ['id'])
    op.alter_column('quote_sources', 'price_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('quote_sources', 'price_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'quote_requests', type_='foreignkey')
    op.drop_column('quote_requests', 'original_quote_id')
    op.drop_column('quote_requests', 'attempt_number')
    op.add_column('project_config_versions', sa.Column('tolerancia_variacao_vs_banco_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_config_versions', type_='foreignkey')
    op.create_foreign_key('project_config_versions_project_id_fkey', 'project_config_versions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_bank_prices', type_='foreignkey')
    op.create_foreign_key('project_bank_prices_config_version_id_fkey', 'project_bank_prices', 'project_config_versions', ['config_version_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_materials_codigo'), table_name='materials')
    op.create_index('ix_materials_codigo', 'materials', ['codigo'], unique=True)
    op.create_index('ix_items_uniqueness', 'items', ['client_id', 'material_id', 'caracteristicas_hash'], unique=False)
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_project_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_api_name'), table_name='financial_transactions')
    op.create_index('ix_financial_transactions_quote', 'financial_transactions', ['quote_id'], unique=False)
    op.create_index('ix_financial_transactions_project', 'financial_transactions', ['project_id'], unique=False)
    op.create_index('ix_financial_transactions_date', 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_financial_transactions_api', 'financial_transactions', ['api_name'], unique=False)
    op.drop_index(op.f('ix_blocked_domains_id'), table_name='blocked_domains')
    op.drop_index(op.f('ix_blocked_domains_domain'), table_name='blocked_domains')
    op.create_index('idx_blocked_domains_domain', 'blocked_domains', ['domain'], unique=False)
    op.create_unique_constraint('blocked_domains_domain_key', 'blocked_domains', ['domain'])
    op.alter_column('blocked_domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('unique_active_config', 'api_cost_config', ['api_name', 'config_type', 'is_active'])
    op.create_index('ix_api_cost_config_is_active', 'api_cost_config', ['is_active'], unique=False)
    op.create_index('ix_api_cost_config_api_name', 'api_cost_config', ['api_name'], unique=False)
    # ### end Alembic commands ###
