"""add_product_link_to_integration_logs

Revision ID: 71d6136f9631
Revises: 4b0c30b467ac
Create Date: 2025-12-14 00:04:20.629223

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '71d6136f9631'
down_revision: Union[str, None] = '4b0c30b467ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_logs', sa.Column('product_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_logs', 'product_link')
    # ### end Alembic commands ###
